# LOGGING
logging:
  level:
    root: INFO

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxx
    password: xxx
    url: jdbc:mysql://ip:3306/demo?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      connection-timeout: 2000
      maximum-pool-size: 20
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      max-lifetime: 570000
      idle-timeout: 500000

# Feign
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 10000
        loggerLevel: full
      gateway-demo-client:
        url: http://spring-boot-inventory.qd-aliyun.haier.net
        Authorization: a15df3a980904ac5aa3e9ceab4dae9aa
#        #异常解码器
#        errorDecoder: com.haier.rdtp.microservice.service.feign.decoder.DemoFeignErrorDecoder
#        #解码器
#        decoder: com.haier.rdtp.microservice.service.feign.decoder.DemoFeignErrorDecoder
        #请求拦截器
        requestInterceptors:
          - com.haier.rdtp.microservice.service.feign.interceptor.DemoFeignInterceptor
  okhttp:
    enabled: true
  httpclient:
    enabled: false
    max-connections: 200
    max-connections-per-route: 50
    time-to-live: 900
    time-to-live-unit: seconds
    connection-timeout: 2000
    follow-redirects: true
    disable-ssl-validation: false

# 用户自定义事件 https://x-docs.haier.net/#/console/alert/custom_event
eventclient:
  serverAddress: http://alertproxy-dev.qd-ctcc.haier.net/api/v1/events
  sendInterval: 30
  sameSendInterval: 300
