# LOGGING
logging:
  level:
    root: INFO

spring:
  # 数据库 DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.138.228.243:3306/demo?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: demo
    password: Haier,123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      connection-timeout: 2000
      maximum-pool-size: 20
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      max-lifetime: 570000
      idle-timeout: 500000
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    database: 15
#    # redis集群
#    cluster:
#      nodes: 1.1.1.1:6379, 1.1.1.1:6379, 1.1.1.1:6379, 1.1.1.1:6379, 1.1.1.1:6379


# Feign
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 10000
        loggerLevel: full
  okhttp:
    enabled: true
  httpclient:
    enabled: false
    max-connections: 200
    max-connections-per-route: 50
    time-to-live: 900
    time-to-live-unit: seconds
    connection-timeout: 2000
    follow-redirects: true
    disable-ssl-validation: false
